version: 2
jobs:
  build:
    docker:
      - image: reflectivedk/circleci-docker-and-gcloud
    steps:
      - checkout
      #- add_ssh_keys
      - setup_remote_docker
      - run:
          name: Authenticate gcloud
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 -d > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
      - run:
          name: Build application Docker image
          command: |
            gcloud docker -- build -t eu.gcr.io/city-7337/modelapi-app .
      - run:
          name: Run modelapi-app
          command: |
            gcloud docker -- run --name modelapi-app -d -p 8080:8080 eu.gcr.io/city-7337/modelapi-app
      - run:
          name: Check running
          command: |
            docker logs modelapi-app
      - deploy:
          name: Push and tag application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              gcloud docker -- push eu.gcr.io/city-7337/modelapi-app
              gcloud -q container images add-tag eu.gcr.io/city-7337/modelapi-app:latest eu.gcr.io/city-7337/modelapi-app:build_$CIRCLE_BUILD_NUM
            fi
